### PR TITLE
Sample App for demo

### PR DESCRIPTION
**Pull request by aj-michael**
The app lets you add vehicles and commodities. When a vehicle is added, the app requests a route for that vehicle from pathfinder-server. Whenever a route is received, that route is drawn. Currently the routes returned start from the first commodity, not the vehicle so it looks really dumb. When that is fixed in pathfinder-server, no change will be needed here.

One major issue: The IP address of the backend server is hardcoded. I'm not sure what the best practice is there. let me know what you think @grovecj

### CODE REVIEW

**Comment by grovecj** [comment]
I don't think cocoa pods is setting up the build setting correctly. It's telling me:  
> No such module 'Starscream'  
  
I can see starscream in finder, but I shouldn't have to manually add it to the project

**Comment by aj-michael** [comment]
Did you do `pod install`?

**Comment by grovecj** [comment]
yeah. I have Starscream.swift, it xcode just can't find it

**Comment by grovecj** [comment]
also, xcode thinks there should be a file called 'pathfinder.swift', but it's not in the repo

**Comment by grovecj** [comment]
It's building now, we're Gucci

**Comment by grovecj** [comment]
Does your map open in russia?

**Comment by aj-michael** [comment]
The app should prompt you to use your location when you first open it, and it should center around you

if you decline those permissions, then yea, probably turkey

**Comment by aj-michael** [comment]
Re: pathfinder.swift, that was a file I had made, but have since deleted. I'm not sure how to convince Xcode to get rid of it.

**Comment by grovecj** [comment]
I got a route, but not the one i expected...

weird route

**Comment by grovecj** [comment]
Actually, i think there may have been a point in the database from the last run that wasn't appearing on the map. It's not particularly robust, but it works well enough for a demo

**Comment by aj-michael** [comment]
Hmmmm. Interesting route. I suspect that the problem is that you opened the app once, added some commodities, closed it, opened it again, more commodities, then routed with a vehicle.

The app currently does not get the commodities from the server because at this time there is no way to get all commodities from the server (since clusters aren't a thing yet in dan's api). So when we get the route, Dan is routing all of the commodities.

I think this is working as intended for the purposes of our demo Tuesday.


Also: WTF Batman?

**Comment by grovecj** [comment]
In regards to the hardcoded ip, eventually we will have a domain domain name to point at

**Pull request merged**
