### PR TITLE
Now with rerouting and reopening sockets with new IPs!

### PR DESCRIPTION
**Pull request by aj-michael**
This will be convenient for the demo tomorrow.

### CODE REVIEW

**Comment by aj-michael** [comment]
Sorry for the late PR @grovecj; I just wanted to update the app to work with the new route push updates in pathfinder-server.

**Comment by grovecj** [comment]
It is still making me manually add Starscream to the project even after I run 
```
pod install
```
If we move forward with this as a demo application, we should make sure that the build process is more streamlined

**Comment by aj-michael** [comment]
Are you opening the project or the workspace?

**Comment by grovecj** [comment]
project

**Comment by grovecj** [comment]
The app builds and runs fine for me

**Comment by aj-michael** [comment]
You need to open the workspace for cocoapods

**Pull request merged**
